# -*- coding: utf-8 -*-
"""Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZaQy3ZC6YH8laGkGcrb2kkAFFvzbs2S
"""

import math, sys

def error() -> None:
  print("Sorry, we don't have this type of math yet")
  sys.exit()

def calculater() -> None:
    print("This is a math calculater")
    print("We have arithmetic (ar), geometry (geo)")

    try:
      math_type: str = input("Which type of math do you want to do? ")

      if math_type in ["arithmetic", "arithmatic", "ar"]:
        print("Ok\nWe have addition, subtraction, multiplication, division, remainder, exponents, sq root, and percentage")
        normal_math_type: str = input("Which one?\n").lower()

        if normal_math_type in ["addition", "add"]:
            num1: int = int(input("First addend? "))
            num2: int = int(input("Second addend? "))
            print(f"The sum is {num1 + num2}!")

        elif normal_math_type in ["subtraction", "subtract"]:
            num1: int = int(input("First number? "))
            num2: int = int(input("Second number? "))
            print(f"The difference is {num1 - num2}!")

        elif normal_math_type in ["multiplication", "multiply"]:
          num1: int = int(input("First factor? "))
          num2: int = int(input("Second factor? "))
          print(f"The product is {num1 * num2}!")

        elif normal_math_type in ["division", "divide"]:
          num1: int = int(input("First number? "))
          num2: int = int(input("Second number? "))
          print(f"The quotient is {num1 / num2}!")

        elif normal_math_type in ["remainder", "remain"]:
          num1: int = int(input("First number? "))
          num2: int = int(input("Second number? "))
          print(f"The remainder is {num1 % num2}!")

        elif normal_math_type in ["ex", "exponent", "exponents"]:
          print("x rasied to the power of y")
          num1: int = int(input("x? "))
          num2: int = int(input("y? "))
          print(f"The answer is {num1 ** num2}!")

        elif normal_math_type in ["square root", "square rootts", "square roott",
                                  "sq roott", "square roots",
                                  "sq rott", "sq root"]:
          num1: int = int(input("First number? "))
          rounded: str = input("Do you you want your answer rounded? ").lower()

          if rounded in ["no"]:
            print(f"The answer is {math.sqrt(num1)}!")

          elif rounded in ["yes"]:
            dec_point: int = int(input("To how many decimal points would you like to round your number to? "))
            print(round(math.sqrt(num1), dec_point))

        elif normal_math_type in ["percentage", "percent", "percents",
                                    "percnts", "prcnts", "precnts", "percnts"]:
          print("x% of y")
          num1: int = int(input("x? "))
          num2: int = int(input("y? "))
          print(f"The answer is {num1/100 * num2}!")

        else:
          error()

      elif math_type in ["geo", "geometry", "geomatry", "geomtry"]:
        shaped_d: str = input("Is your 2_D or 3_d?\n").lower()

        if shaped_d in ["2d", "2_d"]:
          print("Ok\nWe have the area of a rectangle, square, triangle, circle, oval, parallelogram, trapizod, pentagon, hexagon, octagon, and decagon")
          normal_math_type: str = input("Which one?\n").lower()

          if normal_math_type in ["rect", "rectangle"]:
            num1: int = int(input("Length? "))
            num2: int = int(input("Width? "))
            print(f"The answer is {num1 * num2}!")
            # L x W

          elif normal_math_type in ["sq", "square"]:
            num1: int = int(input("Side? "))
            print(f"The answer is {num1 ** 2}!")
            # s x s or s^2

          elif normal_math_type in ["tri", "triangle"]:
            num1: int = int(input("Base? "))
            num2: int = int(input("Height? "))
            print(f"The answer is {num1 * num2 * 0.5}!")
            # 1/2 bh

          elif normal_math_type in ["cir", "circle"]:
            num1: int = int(input("Radius? "))
            print(f"The answer is {3.14 * num1 ** 2}!")
            # πr^2

          elif normal_math_type in ["ov", "oval"]:
            num1: int = int(input("A? "))
            num2: int = int(input("B? "))
            print(f"The answer is {3.14 * num1 * num2}!")
            # π x a x b

          elif normal_math_type in ["parallelogram"]:
            num1: int = int(input("Base? "))
            num2: int = int(input("Height? "))
            print(f"The answer is {num1 * num2}!")
            # b x h

          elif normal_math_type in ["trap", "trapizoid"]:
            num1: int = int(input("Base 1? "))
            num2: int = int(input("Base 2? "))
            num3: int = int(input("Height? "))
            print(f"The answer is {(num1 + num2) / 2 * num3}!")
            # (b1 + b2) / 2 x h

          elif normal_math_type in ["pentagon", "penta"]:
            num1: int = int(input("a? "))
            print(f"The answer is {0.25 * math.sqrt(5 * (5 + 2 * math.sqrt(5))) * num1 ** 2}!")
            # 1/4 x sqrt(5(5 + 2 x sqrt(5)))a^2

          elif normal_math_type in ["hex", "hexa", "hexagon"]:
            num1: int = int(input("a? "))
            print(f"The answer is {3 * math.sqrt(3) / 2 * num1 ** 2}!")
            # 3 x sqrt(3) / 2 x a^2

          elif normal_math_type in ["oct", "octa", "octagon"]:
            num1: int = int(input("a? "))
            print(f"The answer is {2 * (1 + math.sqrt(2)) * num1 ** 2}!")
            # 2 x (1 + sqrt(2))a^2

          elif normal_math_type in ["dec", "deca", "decagon"]:
            num1: int = int(input("a? "))
            print(f"The answer is {2.5 * num1 ** 2 * math.sqrt(5 + 2 * math.sqrt(5))}!")
            # 5/2 a^2 sqrt(5 + 2 sqrt(5))


        elif shaped_d in ["3d", "3_d"]:
          vol_sur: str = input("Do you want to find the volume of the surface area?\n")

          if vol_sur in ["vol", "volume"]:
            print("Ok\nWe have the volume of a sphere")
            normal_math_type: str = input("Which one?\n").lower()

            if normal_math_type in ["sphere", "sphre"]:
              num1: int = int(input("Radius? "))
              print(f"The answer is {4/3 * math.pi * num1 ** 3}!")
              # 4/3πr^3

          elif vol_sur in ["sur", "surface", "surface area"]:
            print("Ok\nWe have the surface area of a sphere")
            normal_math_type: str = input("Which one?\n").lower()

            if normal_math_type in ["sphere", "sphre"]:
              num1: int = int(input("Radius? "))
              print(f"The answer is {4 * math.pi * num1 ** 2}!")
              # 4πr^2

          else:
            error()

    except ValueError:
      error()

calculater()